apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: js-demo1
  name: js-demo1
spec:
  port:
    targetPort: 10000-tcp
  to:
    kind: Service
    name: js-demo1
    weight: 100
